services:
  backend:
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
             gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=backend.settings.production
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    restart: unless-stopped

  frontend:
    ports:
      - "5001:80"
    command: npm run build && npx serve -s build -l 80
    environment:
      - NODE_ENV=production
    restart: unless-stopped