# Generated by Django 5.2 on 2025-05-05 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options_alter_task_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='task',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('global', 'Global')], default='private', max_length=7, verbose_name='Visibility'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user'], name='tasks_task_user_id_0b1849_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['visibility'], name='tasks_task_visibil_82dbfe_idx'),
        ),
    ]
